# Run with: docker-compose up -d
# Services: PostgreSQL (port 5432), Redis (port 6379)

services:
  postgres:
    image: postgres:15
    container_name: pg-urlshortener
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: urls
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-urlshortener
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
